src/server/apps/catalog/urls.py
from django.conf.urls import url
from django.urls import path

from django.views.decorators.cache import cache_page

from . import views

urlpatterns = [

    # View IPTSs for an instrument
    url(r'^$',
        # cache_page(60*60)(views.IPTSs.as_view()), name='list_iptss'),
        (views.IPTSs.as_view()), name='list_iptss'),

    path('<int:intrument_id>/ajax/', views.IPTSsAjax.as_view(), name='list_iptss_ajax'),

    # Just for SNS
    # View all Runs for an instrument
    url(r'^(?P<ipts>[\w\-\.]+)/$',
        views.Runs.as_view(), name='list_runs'),
    url(r'^(?P<ipts>[\w\-\.]+)/ajax-table/$',
        views.RunsAjaxTable.as_view(), name='list_runs_ajax_table'),
    # run detail
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<filename>/SNS/[^\.]+(\.\w+)+)/$',
        views.RunDetail.as_view(), name='run_detail'),

    # HFIR has exp field
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/$',
        views.Runs.as_view(), name='list_runs'),
    # To Zip the contents of the ipts folder (Only HFIR)
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/zip/$',
        views.IptsZip.as_view(), name='zip_ipts'),

    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/ajax/$',
        views.RunsAjax.as_view(), name='list_runs_ajax'),
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/(?P<filename>/HFIR/[^\.]+\.[A-Za-z]{3})/$',
        views.RunDetail.as_view(), name='run_detail'),
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/(?P<filename>/HFIR/[^\.]+\.[A-Za-z]{3})/ajax/$',
        views.RunDetailAjax.as_view(), name='run_detail_ajax'),
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/(?P<filename>/HFIR/[^\.]+\.[A-Za-z]{3})/file/$',
        views.RunFile.as_view(), name='run_file'),

]

src/server/apps/reduction/urls.py
from django.conf.urls import url

from .views import *

# pylint: disable=C0103
urlpatterns = [
    url(r'^$', reduction_list, name='list'),
    url(r'^(?P<pk>\d+)$', reduction_detail, name='detail'),
    url(r'^create$', reduction_create, name='create'),
    url(r'^update/(?P<pk>\d+)$', reduction_update, name='update'),
    url(r'^delete/(?P<pk>\d+)$', reduction_delete, name='delete'),
    url(r'^clone/(?P<pk>\d+)$', reduction_clone, name='clone'),
    url(r'^share/(?P<pk>\d+)$', reduction_share, name='share'),
    url(r'^script/(?P<pk>\d+)$', reduction_script_update, name='script'),
]

src/server/apps/results/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

from .views import *

urlpatterns = [
     # Configurations
    url(r'^$', JobsList.as_view(), name='job_list'),
    url(r'^(?P<pk>\d+)$', JobDetail.as_view(), name='job_detail'),
    url(r'^livelog/(?P<pk>\d+)$', JobLiveLog.as_view(), name='job_log_live'),
    url(r'^live$', TemplateView.as_view(template_name='results/job_live.html'), name='job_list_live'),
    url(r'^zipfiles$', ZipFilesView.as_view(), name='zipfiles'),

    # Cache for 60 * 15 seconds
    # url(r'^result/(?P<pk>\d+)/plot$', cache_page(60 * 15)(ResultPlot.as_view()), name='result_plot'),
]

src/server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Admin
    url(r'^admin/', admin.site.urls),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    # My apps
    url(r'^users/', include(('server.apps.users.urls', 'users'), namespace='users', )),
    url(r'^catalog/', include(('server.apps.catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^reduction/', include(('server.apps.reduction.urls',
                                 'reduction'), namespace='reduction')),
    url(r'^configuration/', include(('server.apps.configuration.urls',
                                     'configuration'), namespace='configuration')),
    url(r'^results/', include(('server.apps.results.urls', 'results'), namespace='results')),
    url(r'^util/', include(('server.util.urls', 'util'), namespace='util')),
    # Redirects all to Homepage
    url(r'^$', RedirectView.as_view(
        url=reverse_lazy('users:profile_view'), permanent=False),
        name='index',
        ),
    # Django remote REST API
    url(r'^api/', include('django_remote_submission.urls')),

]

if settings.DEBUG:
    # Serving files uploaded by a user during development
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/server/apps/reduction/models/abstract.py
from __future__ import unicode_literals

import logging
from pprint import pformat

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.forms.models import model_to_dict
from django_remote_submission.models import Interpreter, Job
from django_auth_ldap.backend import LDAPBackend
from django.contrib.postgres.fields import JSONField

from server.apps.catalog.models import Instrument
from server.util.models import ModelMixin
from server.apps.users.ldap_util import LdapSns

logger = logging.getLogger(__name__)  # pylint: disable=C0103

'''
Abstract models for SANS

Configuration - 1 to many - Reductions
Reduction - 1 to many - Entries
'''

################################################################################
# Actions
################################################################################

class Actions(models.Model, ModelMixin):
    '''
    '''
    
    created_date = models.DateTimeField(auto_now_add=True)

    modified_date = models.DateTimeField(auto_now=True)

    description = models.CharField(max_length=256)

    instrument = models.ForeignKey(
        Instrument, on_delete=models.CASCADE,
        related_name="%(class)s_instruments",
        related_query_name="%(class)s_instrument",
    )

    script_interpreter = models.ForeignKey(
        Interpreter,
        null=True,
        on_delete=models.CASCADE,
        related_name="%(class)s_interpreters",
        related_query_name="%(class)s_interpreter",
    )

    script_template_path  = models.CharField(
        max_length=256,
        help_text="Where the script template is. E.g. /SNS/HYS/shared/templates/reduce.tpl"
    )

    destination_directory_path_template  = models.CharField(
        max_length=256,
        help_text="Where the script is going to be copied and may be executed."
            r" E.g. /SNS/HYS/%(ipts_number)s/shared/reduce/%(hash)s"
    )

    django_remote_submission_tasks = models.CharField(
        max_length=32,
        help_text="Tasks in Django Remote Submission: copy_job_to_server, submit_job_to_server",
    )

    def __str__(self):
        return "{}".format(self.description)


################################################################################
# Reduction
################################################################################

class ReductionManager(models.Manager):
    '''
    This is a general reduction manager.
    '''

    use_for_related_fields = True

    def clone(self, pk):
        '''
        Clones the Reduction object and related regions
        '''

        obj = self.get(id=pk)
        # Let's clone the related entries
        new_regions = []
        for region in obj.regions.all():
            region.pk = None
            region.save()
            new_regions.append(region)
        users = obj.users.all()

        obj.pk = None  # setting to None, clones the object!
        obj.save()
        # obj.regions = new_regions
        obj.regions.set(new_regions)
        obj.title += " (cloned)"
        obj.save()
        obj.users.add(*users)
        return obj

    def to_json(self, pk):
        '''
        Gets this reduction object in json format
        serializes: reduction and related regions and associated configuration
        Not for use in SANS:
        1 Reduction has 1 Configuration
        1 Reduction has multiple Regions
        '''
        obj = self.select_related().get(pk=pk)
        obj_json = model_to_dict(obj)
        obj_json["users"] = ", ".join(user.username for user in obj.users.all())
        obj_json["regions"] = []
        for region in obj.regions.select_related():
            d = model_to_dict(region)
            obj_json["regions"].append(d)
        obj_json['configuration'] = model_to_dict(obj.configuration)
        obj_json['action'] = model_to_dict(obj.action)
        obj_json['action']['script_interpreter'] = \
            model_to_dict(obj.action.script_interpreter)
        
        if hasattr(obj.configuration, 'masks') and \
                obj.configuration.masks is not None:
            obj_json['configuration']['masks'] = []
            for mask in obj.configuration.masks.select_related():
                d = model_to_dict(mask)
                obj_json['configuration']['masks'].append(d)
            
        # logger.debug(pformat(obj_json))
        return obj_json

    def _get_user(self, uid):
        '''
        If the user is not in the DB already
        gets it from LDAP and populate the DB with it
        returns the User object or None if it doesn't exist
        '''
        if not get_user_model().objects.filter(username=uid).exists():
            # this new_uid is not on the database
            logger.debug("UID %s does not exist in the DB. "
                         "Getting it from LDAP.", uid)
            user = LDAPBackend().populate_user(uid)
            if not user:
                logger.warning("UID %s is known to belong to this IPTS but does"
                               " not exist in LDAP... Skipping it.", uid)
                return None
        return get_user_model().objects.get(username=uid)

    def share(self, pk, ipts):
        '''
        For an IPTS get all user uids from LDAP and assign them to the obj.
        '''
        uids = LdapSns().get_all_uids_for_an_ipts(ipts)
        logger.debug("Share: Users for IPTS %s : %s", ipts, pformat(uids))
        
        obj = self.get(id=pk)
        # obj.users.clear()
        for uid in uids:
            user_obj = self._get_user(uid)
            if user_obj is not None:
                obj.users.add(user_obj)
                obj.configuration.users.add(user_obj)
                obj.save()
                logger.debug("Share: User {} added to Reduction '{}' and Configuration '{}'".format(
                    user_obj, obj, obj.configuration))
        return obj

class Reduction(models.Model, ModelMixin):
    '''
    '''

    title = models.CharField(max_length=256)

    created_date = models.DateTimeField(auto_now_add=True)

    modified_date = models.DateTimeField(auto_now=True)

    # Additional parameters: e.g. Runs for executing the algorithm
    parameters = JSONField(null=True, default=[], blank=True,)

    script = models.TextField(
        blank=True,
        help_text="Python script generated from the reduction entry. \
        If the script was generated already just shows it!"
    )

    instrument = models.ForeignKey(
        Instrument, on_delete=models.CASCADE,
        related_name="%(class)s_instruments",
        related_query_name="%(class)s_instrument",
    )
    
    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        #related_name="%(class)s_users",
        #related_query_name="%(class)s_user",
    )

    action = models.ForeignKey(
        Actions,
        verbose_name="Action to take for the reduction",
        null=True,
        on_delete=models.CASCADE,
        related_name="%(class)s_action",
        related_query_name="%(class)s_action",
        help_text="Pick an action for your reduction",
    )

    job = models.ForeignKey(
        Job,
        null=True,
        on_delete=models.CASCADE,
        related_name="%(class)s_job",
        related_query_name="%(class)s_job",
    )

    # Manager
    objects = ReductionManager()

    class Meta:
        ordering = ["id"]
        abstract = True

    def __str__(self):
        return self.title

################################################################################
# Region
################################################################################

class RegionManager(models.Manager):
    '''
    Queries go here!!
    '''
    use_for_related_fields = True


class Region(models.Model, ModelMixin):
    '''
    Region can be low, medium or high Q
    This will be a formset from Reduction
    '''

    created_date = models.DateTimeField(auto_now_add=True)

    modified_date = models.DateTimeField(auto_now=True)

    # Manager
    objects = RegionManager()

    class Meta:
        abstract = True
        ordering = ["id"]

src/server/apps/reduction/forms/abstract.py
'''
Created on Jan 8, 2016
@author: rhf
'''
from crispy_forms.bootstrap  import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (
    Submit, Button, Layout, Fieldset, HTML,
)
from crispy_forms.bootstrap import Field, InlineCheckboxes

from django.forms import HiddenInput, BooleanField


# class SubmitWithCss(Submit):
#     '''
#     Overries the Submit button to remove the default css:
#     btn btn-primary
#     '''
#     def __init__(self, *args, **kwargs):
#         self.field_classes = 'btn'
#         super(SubmitWithCss, self).__init__(*args, **kwargs)

class ReductionForm(object):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal'
        self.helper.render_required_fields = True
        self.helper.form_tag = False # To NOT render the form csrf fields etc..

    class Meta:
        exclude = [
            'users', 'instrument', 'parameters', 'script', 'job', 'action', 
        ]
        #widgets = {'script': HiddenInput()}

class ReductionScriptForm(object):
    def __init__(self, *args, **kwargs):
        super(ReductionScriptForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal'
        
    class Meta:
        fields = [ 'action', 'parameters', 'script',]
        #exclude = ['user', 'instrument']
        #widgets = {'parameters': HiddenInput()}
        


class RegionForm(object):
    def __init__(self, *args, **kwargs):
        super(RegionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.render_required_fields = True
        self.helper.form_tag = False
        self.helper.render_hidden_fields = True

    class Meta:
        fields = '__all__'
        #widgets = {'entries': HiddenInput()}

src/server/apps/reduction/views/sans/hfir/biosans/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, UpdateView,
)

from server.apps.configuration.models.sans.hfir.biosans import Configuration
from server.apps.reduction.forms.sans.hfir.biosans import (
    ReductionForm,
    ReductionScriptForm,
    RegionInlineFormSetCreate,
    RegionInlineFormSetUpdate,
)
from server.apps.reduction.models.sans.hfir.biosans import Reduction
from server.apps.reduction.views.mixins import (
    ReductionCreateMixin,
    ReductionDeleteMixin,
    ReductionMixin,
    ReductionCloneMixin,
    ReductionUpdateMixin,
    ReductionScriptUpdateMixin,
)

from ...mixins import SANSMixin


class ReductionList(LoginRequiredMixin, ReductionMixin, ListView):
    '''
    List all Reduction.
    '''
    template_name = 'reduction/list.html'
    model = Reduction


class ReductionDetail(LoginRequiredMixin, ReductionMixin, DetailView):
    '''
    '''
    template_name = 'reduction/detail.html'
    model = Reduction


class ReductionCreate(LoginRequiredMixin, ReductionCreateMixin, SANSMixin, CreateView):
    '''
    Create a new entry!
    '''
    template_name = 'reduction/sans/form.html'
    model = Reduction
    model_configuration = Configuration
    form_class = ReductionForm
    formset_class = RegionInlineFormSetCreate
    success_url = reverse_lazy('reduction:list')


class ReductionDelete(LoginRequiredMixin, ReductionDeleteMixin, DeleteView):

    template_name = 'reduction/confirm_delete.html'
    model = Reduction
    success_url = reverse_lazy('reduction:list')

class ReductionClone(LoginRequiredMixin, ReductionCloneMixin, UpdateView):

    template_name = 'reduction/detail.html'
    model = Reduction
    model_configuration = Configuration
    form_class = ReductionForm
    formset_class = RegionInlineFormSetCreate


class ReductionUpdate(LoginRequiredMixin, ReductionUpdateMixin, SANSMixin, UpdateView):
    '''
    Edit a Reduction (The spreadsheet)
    '''
    template_name = 'reduction/sans/form.html'
    model = Reduction
    model_configuration = Configuration
    form_class = ReductionForm
    formset_class = RegionInlineFormSetUpdate
    success_url = reverse_lazy('reduction:list')


class ReductionScriptUpdate(LoginRequiredMixin, ReductionScriptUpdateMixin, UpdateView):

    template_name = 'reduction/script_form.html'
    model = Reduction
    model_configuration = Configuration
    form_class = ReductionScriptForm
    formset_class = RegionInlineFormSetUpdate
    success_url = reverse_lazy('reduction:list')

src/templates/reduction/confirm_delete.html
 {% extends "base.html" %}
 
 {% load staticfiles %}
 
 {% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'reduction:list' %}">Reduction</a></li>
        <li class="active">{{ object }}</li>
    </ol>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="jumbotron">
      <p>Are you sure you want to delete "{{ object }}"?</p>
        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Yes</button>
            <a href="{% url 'reduction:detail' object.id %}"
                id="cancel" name="cancel" class="btn btn-default">Cancel</a>
        </form>

  </div>
</div>
{% endblock %}

src/templates/reduction/detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block header %}
{{ block.super }}
<!-- handsontable -->
<link rel="stylesheet" type="text/css" href='{% static "thirdparty/handsontable/handsontable.full.min.css" %}'>
<style>
.list-group > li:nth-child(even) {
  background: #f5f5f5;
}
</style>
{% endblock %}

{% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'reduction:list' %}">Reduction</a></li>
        <li class="active">{{ object }}</li>
    </ol>
</div>
{% endblock %}

{% block content %}

<div class="container">

    <div class="page-header">
       <h1>Reduction details <small> {{ object }}</small></h1>
    </div>

	<!-- This is the reduction info -->
    <div class="container-fluid">
            <ul class="list-group">
                {% for f in object.get_all_fields %}
	                <li class="list-group-item">
                        {% if f.name == "script" and f.value %}
                            <a role="button" data-toggle="collapse" data-target="#code"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Click to see the script</a>
                            <div id="code" class="collapse">
                            <pre><code>{{f.value}}</code></pre>
                            </div>
                        {% elif f.name == "parameters" and f.value %}
                            <pre><code>{{f.value}}</code></pre>
						{% else %}
							<strong>{{f.label|capfirst}}</strong>
							<span class="pull-right">{{f.value|escape|urlize|linebreaks}}</span>
						{% endif %}
	                </li>
	            {% endfor %}
            </ul>
    </div>
    <hr/>

    <!-- This is the action -->
    {% if object.action %}
    <div class="container-fluid">
        <h3>Action</h3>
        <ul class="list-group">
            {% for f in object.action.get_all_fields %}
            <li class="list-group-item">
                    <strong>{{f.label|capfirst}}</strong>
                    <span class="pull-right">{{f.value|escape|urlize|linebreaks}}</span>
            </li>
            {% endfor %}
        </ul>
    </div>
    <hr/>
    {% endif %}

    <!-- This is the region (low,med,high) info -->
    <div class="container-fluid">
        {% for entry in object.regions.all %}
        <h3>{{entry}}</h3>
        <ul class="list-group">
            {% for f in entry.get_all_fields %}
                <li class="list-group-item">
                    {% if f.name == "entries" %}
                        <div id="hot-{{forloop.counter}}" value="{{f.value}}"></div>
                    {% else %}
                        <strong>{{f.label|capfirst}}</strong>
                        <span class="pull-right">{{f.value|escape|urlize|linebreaks}}</span>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
        {% endfor %}
    </div>

    <p>
            <a class="btn btn-primary" data-toggle="tooltip" data-placement="top" href="{% url 'reduction:update' object.pk %}"
            title="Click to edit the details of this configuration."><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit</a>

        <a id="button_delete" class="btn btn-danger" data-toggle="tooltip" data-placement="top" href="{% url 'reduction:delete' object.pk %}"
            title="Delete this reduction and associated regions."><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete...</a>

        <a class="btn btn-primary" data-toggle="tooltip" data-placement="top" href="{% url 'reduction:clone' object.pk %}"
            title="Creates a copy of this reduction as you might need a few different parameters.">Duplicate</a>
          
        <a class="btn btn-primary" data-toggle="tooltip" data-placement="top" href="{% url 'reduction:share' object.pk %}"
            title="Share the reduction among the members of the same IPTS"><span class="glyphicon glyphicon-share" aria-hidden="true"></span> Share</a>


    </p>
    <p>
        &nbsp;
    </p>
    <p>
        <a class="btn btn-primary" data-toggle="tooltip" data-placement="top" href="{% url 'reduction:script' object.id  %}"
            title="Generates a python script and prepare the job submission.">Launch...</a>

        

        
        {% if object.job is not None %}
        <a class="btn btn-primary" data-toggle="tooltip" data-placement="top" href="{% url 'results:job_detail' object.job.id  %}"
		    title="See the Job info and Results for this reduction.">Results...</a>
        {% endif %}
        
        <a id="cancel" class="btn btn-default" data-toggle="tooltip" data-placement="top" onclick="window.history.back()"
        	href="#" title="Goes back....">Cancel</a>
    </p>
</div>
{% endblock %}

{% block footer_js%}
{{ block.super }}
<!-- For the form symbols -->
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML" async>
</script>

<script src='{% static "thirdparty/handsontable/handsontable.full.min.js" %}'></script>
<!-- page script -->
<script>

/******************* handsontable *************************/

// Let's get the entries: id_regions-0-entries
var entriesSelectors = $('[id ^=hot]');

// For every input field add a div anchor to place the spreadsheet
$.each( entriesSelectors, function( i, selector ) {
    var dataAsString = $(selector).attr('value');
	dataAsString = dataAsString.replace(/\'/g,'"')
	dataAsString = dataAsString.replace(/None/g,'null')
	var data =  JSON.parse(dataAsString);
    //console.log(data);
    var options = {
        data: data,
        height: 200,
        minSpareRows: 0,
        stretchH: 'all',
        columnSorting: true,
        contextMenu: true,
        autoWrapRow: true,
        rowHeaders: true,
        contextMenu: true,
        outsideClickDeselects: false,
		readOnly: true,
        columns: [
            { data: "name" },
            { data: "thickness"},
            { data: "sample_scattering"},
            { data: "sample_transmission"},
            { data: "backgroung_scattering"},
            { data: "backgroung_transmission"}
        ],
        colHeaders: ["Name", "Thickness", "Sample Scattering", "Sample Transmission", "Backgroung Scattering",
                     "Backgroung Transmission"],

    };
    $(selector).handsontable(options);
    //remove it from the <ul>
    //$(selector).parent().parent().append($(selector));

});


</script>
{% endblock %}

src/templates/reduction/list.html
 {% extends "base.html" %}
 
 {% load staticfiles %}
 
 {% block header %}
 {{ block.super }}
<link rel="stylesheet" type="text/css" href='{% static "thirdparty/DataTables/datatables.min.css" %}'>
{% endblock %}

{% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="">Reduction</a></li>
        <li class="active">List</li>
    </ol>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Reduction<small> list</small></h1>
    </div>

    <table id="table_configuration" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Date created</th>
                <th>Date modified</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{object.id}}</td>
                <td><a href="{% url 'reduction:detail' object.id %}"
                    title="Click to see the details of this reduction."><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span> {{object.title}}</a>
                	</td>
                <td>{{object.created_date | date:"DATETIME_FORMAT" }}</td>
                <td>{{object.modified_date | date:"DATETIME_FORMAT" }}</td>
                <td>
                    <a data-toggle="tooltip" data-placement="right" href="{% url 'reduction:update' object.pk %}"
                        title="Click to edit the details of this reduction."><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
                    &nbsp;
                    <a data-toggle="tooltip" data-placement="right" href="{% url 'reduction:delete' object.pk %}"
                        title="Click to delete this reduction."><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Date created</th>
                <th>Date modified</th>
                <th>Actions</th>
            </tr>
        </tfoot>
    </table>
</div>
{% endblock %}

{% block footer_js%}
{{ block.super }}
<script src='{% static "thirdparty/DataTables/datatables.min.js" %}'></script>
<!-- page script -->
<script>
        $(function () {
            $("#table_configuration").DataTable({
                "lengthMenu": [[20, 50, 100, -1], [20, 50, 100, "All"]],
                "order": [[ 3, 'desc' ]],
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": true,
                columnDefs: [
                    {
                        "targets": 4,
                        //"visible": false,      // And making this columns invisible ...
                        "orderable" : false,
                        "searchable": false,
                        "width": "10%",
                        "className": "text-center"
                    },
                    {
                        "targets": [2,3],
                        "className": "text-right"
                    }
                ]
            });
        });
    </script>
{% endblock %}