src/server/apps/catalog/urls.py
from django.conf.urls import url
from django.urls import path

from django.views.decorators.cache import cache_page

from . import views

urlpatterns = [

    # View IPTSs for an instrument
    url(r'^$',
        # cache_page(60*60)(views.IPTSs.as_view()), name='list_iptss'),
        (views.IPTSs.as_view()), name='list_iptss'),

    path('<int:intrument_id>/ajax/', views.IPTSsAjax.as_view(), name='list_iptss_ajax'),

    # Just for SNS
    # View all Runs for an instrument
    url(r'^(?P<ipts>[\w\-\.]+)/$',
        views.Runs.as_view(), name='list_runs'),
    url(r'^(?P<ipts>[\w\-\.]+)/ajax-table/$',
        views.RunsAjaxTable.as_view(), name='list_runs_ajax_table'),
    # run detail
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<filename>/SNS/[^\.]+(\.\w+)+)/$',
        views.RunDetail.as_view(), name='run_detail'),

    # HFIR has exp field
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/$',
        views.Runs.as_view(), name='list_runs'),
    # To Zip the contents of the ipts folder (Only HFIR)
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/zip/$',
        views.IptsZip.as_view(), name='zip_ipts'),

    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/ajax/$',
        views.RunsAjax.as_view(), name='list_runs_ajax'),
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/(?P<filename>/HFIR/[^\.]+\.[A-Za-z]{3})/$',
        views.RunDetail.as_view(), name='run_detail'),
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/(?P<filename>/HFIR/[^\.]+\.[A-Za-z]{3})/ajax/$',
        views.RunDetailAjax.as_view(), name='run_detail_ajax'),
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/(?P<filename>/HFIR/[^\.]+\.[A-Za-z]{3})/file/$',
        views.RunFile.as_view(), name='run_file'),

]

src/server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Admin
    url(r'^admin/', admin.site.urls),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    # My apps
    url(r'^users/', include(('server.apps.users.urls', 'users'), namespace='users', )),
    url(r'^catalog/', include(('server.apps.catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^reduction/', include(('server.apps.reduction.urls',
                                 'reduction'), namespace='reduction')),
    url(r'^configuration/', include(('server.apps.configuration.urls',
                                     'configuration'), namespace='configuration')),
    url(r'^results/', include(('server.apps.results.urls', 'results'), namespace='results')),
    url(r'^util/', include(('server.util.urls', 'util'), namespace='util')),
    # Redirects all to Homepage
    url(r'^$', RedirectView.as_view(
        url=reverse_lazy('users:profile_view'), permanent=False),
        name='index',
        ),
    # Django remote REST API
    url(r'^api/', include('django_remote_submission.urls')),

]

if settings.DEBUG:
    # Serving files uploaded by a user during development
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/server/apps/catalog/views.py
import logging
import os
import os.path
import zipfile
from io import BytesIO

from pprint import pformat

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import select_template
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, View
from django.db import transaction
from django.contrib.auth.decorators import login_required
from server.apps.users.ldap_util import LdapSns
from django.conf import settings
from django.http import HttpResponseForbidden
from django.http import HttpResponse
from django.http import FileResponse
from django.urls import reverse

from django.http import HttpResponse, HttpResponseNotFound
from .models import Facility, Instrument
from .oncat.facade import Catalog

logger = logging.getLogger(__name__)


class CatalogMixin(object):
    '''
    Context enhancer for the Catalog
    '''

    def dispatch(self, request, *args, **kwargs):
        '''
        First method being called
        Usefull for debug and set member variables
        '''
        # logger.debug('Token in session (starting the request):\n%s',
        #              pformat(request.session.get('token')))

        self.facility = self.request.user.profile.instrument.facility
        self.instrument = self.request.user.profile.instrument

        self.catalog = Catalog(
            facility=self.facility.name,
            technique=self.instrument.technique,
            instrument=self.instrument.catalog_name,
            request=self.request
        )

        return super(CatalogMixin, self).dispatch(request, *args, **kwargs)

    def get_template_names(self):
        """
        Let's override this function.
        Returns a list of priority templates to render. From specific to general.
        facility/instrument/self.template
        facility/self.template
        self.template
        Note that the method caling this must have self.template_name defined!!
        """

        facility_name = self.facility.name.lower()
        instrument_name = self.instrument.name.lower()

        return [
            os.path.join('catalog', facility_name, instrument_name, self.template_name),
            os.path.join('catalog', facility_name, self.template_name),
            os.path.join('catalog', self.template_name),
        ]


class IPTSs(LoginRequiredMixin, CatalogMixin, TemplateView):
    '''
    List of IPTSs
    '''
    template_name = 'list_iptss.html'

    def get_context_data(self, **kwargs):
        logger.debug("Listing IPTSs for: {}".format(self.catalog))
        iptss = self.catalog.experiments()
        context = super(IPTSs, self).get_context_data(**kwargs)
        context['iptss'] = iptss
        # logger.debug("Catalog returned:\n%s", pformat(iptss))
        return context

class IPTSsAjax(LoginRequiredMixin, TemplateView):
    '''
    List of RUNS for a given ipts as ajax
    '''

    def get(self, request, *args, **kwargs):

        instrument_id = kwargs['intrument_id']
        instrument_obj = Instrument.objects.get(id=instrument_id)
        facility_obj = instrument_obj.facility


        facility = facility_obj
        instrument = instrument_obj

        catalog = Catalog(
            facility=facility.name,
            technique=instrument.technique,
            instrument=instrument.catalog_name,
            request=self.request
        )

        iptss = catalog.experiments()
        iptss_filtered = [ {k: v for k, v in ipts.items() if k in [
            "exp", "ipts", "title"
        ]} for ipts in iptss]
        return JsonResponse(iptss_filtered, status=200, safe=False)

class Runs(LoginRequiredMixin, CatalogMixin, TemplateView):
    '''
    List of runs for a given instrument
    '''

    template_name = 'list_runs.html'

    def get_context_data(self, **kwargs):
        ipts = kwargs['ipts']
        exp = kwargs.get('exp')
        logger.debug('Getting runs from catalog: %s', self.catalog)
        runs = self.catalog.runs(ipts, exp)
        context = super(Runs, self).get_context_data(**kwargs)
        # logger.debug("Sent to template:\n%s", pformat(runs))
        context['runs'] = runs
        return context


class RunsAjax(LoginRequiredMixin, CatalogMixin, TemplateView):
    '''
    List of RUNS for a given ipts as ajax
    '''

    def get(self, request, *args, **kwargs):

        ipts = kwargs['ipts']
        exp = kwargs.get('exp')
        logger.debug("Listing RunsAjax for: %s -> %s %s",
                     self.catalog, ipts, exp)
        runs = self.catalog.runs(ipts, exp)
        # Let's filter the catalog results and just provide a subset of data"
        runs_out = [
            {
                'url': reverse('catalog:run_file', kwargs={
                    'ipts': ipts,
                    'exp': exp,
                    'filename': r['location'],
                }),
                'scan': r['metadata']['scan'],
                'scan_title': r['metadata']['scan_title'],
            } for r in runs if 'metadata' in r
        ]

        # runs_out = []
        # for r in runs:
        #     print(80*"*", r)
        #     runs_out.append(
        #         {
        #             'url': reverse('catalog:run_file', kwargs={
        #                 'ipts': ipts,
        #                 'exp': exp,
        #                 'filename': r['location'],
        #             }),
        #             'scan': r['metadata']['scan'],
        #             'scan_title': r['metadata']['scan_title'],
        #         }
        #     )

        # logger.debug(pformat(iptss))
        return JsonResponse(runs_out, status=200, safe=False)


class RunsAjaxTable(LoginRequiredMixin, CatalogMixin, TemplateView):
    '''
    List of RUNS for a given ipts as ajax

    Output is a list of:
    {
        "location": "/SNS/HYS/IPTS-21013/nexus/HYS_189090.nxs.h5",
        "modified": "2018-07-06T12:13:07.616-04:00",
        "metadata": {
            "total_counts": 8539,
            "run_number": "189090",
            "end_time": "2018-07-06T12:12:48.180432666-04:00",
            "duration": 64.24916076660156,
            "start_time": "2018-07-06T12:11:43.931269666-04:00",
            "title": "Align:check alignment in air"
        },
        "title": "Align:check alignment in air"
    },
    '''

    def get(self, request, *args, **kwargs):

        ipts = kwargs['ipts']
        exp = kwargs.get('exp')
        logger.debug("Listing RunsAjax for: %s -> %s %s",
                     self.catalog, ipts, exp)
        runs = self.catalog.runs(ipts, exp)

        runs_out = [
            [i['metadata']['run_number'], i['title'], i['location']] for i in runs
        ]

        # runs_out = {
        #     'data': runs_out
        # }
        
        # logger.debug(pformat(iptss))
        return JsonResponse(runs_out, status=200, safe=False)

class RunDetail(LoginRequiredMixin, CatalogMixin, TemplateView):
    '''
    Detail of run
    '''

    template_name = 'run_detail.html'

    def get_context_data(self, **kwargs):

        ipts = kwargs['ipts']
        exp = kwargs.get('exp')
        filename = kwargs['filename']
        logger.debug('Getting run detail from catalog: %s %s %s %s',
                     self.catalog, ipts, exp, filename)
        run = self.catalog.run(ipts, filename)
        context = super(RunDetail, self).get_context_data(**kwargs)
        context['run'] = run
        return context


class RunDetailAjax(LoginRequiredMixin, CatalogMixin, TemplateView):
    '''
    Get the run detail but in ajax format
    '''

    def get(self, request, *args, **kwargs):

        ipts = kwargs['ipts']
        exp = kwargs.get('exp')
        filename = kwargs['filename']
        logger.debug('Getting run detail from catalog: %s %s %s %s',
                     self.catalog, ipts, exp, filename)
        run = self.catalog.run(ipts, filename)
        run.pop('data', None)
        return JsonResponse(run, status=200, safe=False)


class RunFile(LoginRequiredMixin, CatalogMixin, TemplateView):
    '''
    Raw File for a run
    Downloadable as attachment
    It first verifies if the user has permissions
    '''

    def get(self, request, *args, **kwargs):
        ipts = kwargs['ipts']
        filename = kwargs['filename']
        logger.debug("RunFile: Fetching file: %s", filename)

        all_groups_for_this_user = list(
            request.user.groups.values_list('name', flat=True))

        if ipts not in all_groups_for_this_user \
                and self.instrument.ldap_group_name not in all_groups_for_this_user \
                and settings.LDAP_ADMIN_GROUP not in all_groups_for_this_user:
            logger.error("User {} belongs to groups: {}."
                         " It has no permission to see {}.".format(
                    request.user, all_groups_for_this_user, ipts
                )
            )
            return HttpResponseForbidden()

        # Check if the file exists
        if not os.path.exists(filename):
            logger.debug('File {} not found.'.format(filename))
            return HttpResponseNotFound('File {} not found.'.format(filename))

        response = FileResponse(open(filename, 'rb'))
        response['Content-Disposition'] = "attachment; filename={}".format(filename)
        # wrapper = FileWrapper(open(filename))
        # response = HttpResponse(wrapper, content_type='text/plain')
        # response['Content-Length'] = os.path.getsize(filename)
        return response



class IptsZip(LoginRequiredMixin, CatalogMixin, TemplateView):
    '''
    Zip the IPTS folder and return it as
    '''

    def _zipdir(self, path, zip_handler):
        '''
        ziph is zipfile handle
        '''
        for root, dirs, files in os.walk(path):
            for file in files:

src/templates/catalog/list_iptss.html
{% extends "base.html" %}

{% load staticfiles %}

{% block header %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href='{% static "thirdparty/DataTables/datatables.min.css" %}'>
{% endblock %}

{% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li class="active">IPTSs for {{user.profile.instrument}}</li>
    </ol>
</div>
{% endblock %}

{% block content %}
<div class="container">
	
    <div class="page-header">
        <h1>Catalog <small> List of IPTSs for {{user.profile.instrument}}</small></h1>
    </div>

    {% if iptss %}
    <table id="tableipts" class="table table-bordered table-striped">
        <thead>
            <th>IPTS</th>
            {% if iptss.1.exp %}<th>Experiment</th>{% endif %}
            <th>Title</th>
            <th>Nr. Scans</th>
            <th>Date modified</th>
            <th>Users</th>
            <th></th>
        </thead>
        <tbody>
            {% for ipts in iptss %}
                {# HFIR Case (They have IPTS + Exp) #}
                {% for exp in ipts.exp %}                    
                    {% if exp|slice:":3" == "exp" %}
                    <tr>
                        <td>{{ipts.ipts}}</td>
                        <td><a href="{% url 'catalog:list_runs' ipts.ipts exp %}" data-toggle="tooltip" data-placement="right" 
                            title="Click to see the runs for this experiment...">{{exp}}</a></td>
                        <td>{{ipts.title}}</td>
                        <td>{{ipts.size}}</td>
                        <td>{{ipts.modified | date:"DATETIME_FORMAT"}}</td>
                        <td>
                            {% for user in ipts.users %}
                                <span data-toggle="tooltip" title="{{user.name}}">{{ user.id }}</span>
                                {% if not forloop.last %}|{% endif%}
                            {% endfor %}
                        </td>
                        <td>
                            {% for user in ipts.users %} {{user.name}} {% endfor %}
                        </td>
                    </tr>
                    {% endif %}
                {% empty %}
                    {# SNS Case #}
                    <tr>
                        <td><a href="{% url 'catalog:list_runs' ipts.ipts %}" data-toggle="tooltip"
                            data-placement="right" title="Click to see the runs for this experiment...">{{ipts.ipts}}</a></td>
                        <td>{{ipts.title}}</td>
                        <td>{{ipts.size}}</td>
                        <td>{{ipts.modified | date:"DATETIME_FORMAT"}}</td>
                        <td>
                            {% for user in ipts.users %}
                                <span data-toggle="tooltip" title="{{user.name}}">{{ user.id }}</span>
                                {% if not forloop.last %}|{% endif%}
                            {% endfor %}
                        </td>
                        <td>
                            {% for user in ipts.users %} {{user.name}} {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
        <tfoot>
            <th>IPTS</th>
            {% if iptss.1.exp %}<th>Experiment</th>{% endif %}
            <th>Title</th>
            <th>Nr. Scans</th>
            <th>Date modified</th>
            <th>Users</th>
            <th></th>
        </tfoot>
    </table>
    {% else %}
    <div class="alert alert-danger" role="alert">
        <strong>No Data to show!</strong>
        <p>Either you have no IPTSs available for this instrument or the ONCat is down...</p>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block footer_js%}
{{ block.super }}
<script src='{% static "thirdparty/DataTables/datatables.min.js" %}'></script>
<!-- This CDN is for natural sorting : see columnDefs type: 'natural' -->
<script src='https://cdn.datatables.net/plug-ins/1.10.13/sorting/natural.js'></script>
<!-- page script -->
<script>
        // To show the complete name once we over ucams uid
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip(); 
        });
        
        tableIPTSsConfiguration = {
            lengthMenu: [[20, 50, 100, -1], [20, 50, 100, "All"]],
            paging: true,
            lengthChange: true,
            searching: true,
            ordering: true,
            info: true,
            autoWidth: false,
            columnDefs: [
                { type: 'natural', targets: 0 },
                {% if iptss.0.exp %}
                { type: "date", targets: 4 },
                { width: "50%", targets: 2 },
                { width: "10%", targets: 5 },
                { visible: false, searchable: true, targets: 6 }
                {% else %}
                { type: "date", targets: 3 },
                { width: "50%", targets: 1 },
                { width: "10%", targets: 4 },
                { visible: false, searchable: true, targets: 5 }
                {% endif %}
            ],
            {% if iptss.0.exp %}
            order: [[ 4, 'desc' ]]
            {% else %}
            order: [[ 3, 'desc' ]]
            {% endif %}
        };
        $("#tableipts").DataTable(tableIPTSsConfiguration);

</script>
{% endblock %}

src/templates/catalog/list_runs.html
 {% extends "base.html" %}

 {% load staticfiles %}

 {% block header %}
 {{ block.super }}
<link rel="stylesheet" type="text/css" href='{% static "thirdparty/DataTables/datatables.min.css" %}'>
<link rel="stylesheet" type="text/css" href='{% static "thirdparty/DataTables/Buttons/css/buttons.bootstrap.min.css" %}'>
{% endblock %}

{% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'catalog:list_iptss' %}">Catalog for {{user.profile.instrument}}</a></li>
		<li class="active">{{ipts}} {%if exp %} :: {{exp}} {%endif%}</li>
    </ol>
</div>
{% endblock %}

{% block content %}
<div class="container">


{% block content_header %}
    <div class="page-header">
		<h1>Catalog {{user.profile.instrument}} <small> Runs for {{ipts}} {%if exp %} :: {{exp}} {%endif%} </small></h1>

		{# If we are at hfir show download stuff #}
		{%if exp %}
		<p>
		<a class="btn btn-default pull-right" href="{% url 'catalog:zip_ipts' ipts exp %}" data-toggle="tooltip" data-placement="bottom" title="This can be extremely slow!!">
			<span class="glyphicon glyphicon-download-alt"></span> Download this experiment contents</a>
		</p>
		{% endif %}
	</div>
{% endblock content_header %}

<table id="tableruns" class="table table-bordered table-striped">
	<thead>
		<tr>
			{% block table_header %}
			<th>Run</th>
			<th>Title</th>
			<th>Last modified</th>
			{% endblock table_header %}
		</tr>
	</thead>
	<tbody>
		{% for run in runs %}
		<tr>
			{% block table_content %}
			{# Make sure that either the run number or the file name are available#}
			<td>
				{%if exp %}
				<a href="{% url 'catalog:run_detail' ipts exp run.location %}">{{run.filename}} </a>
				{% else %}
				<a href="{% url 'catalog:run_detail' ipts run.location %}">{{run.metadata.run_number}}</a>
				{% endif %}
			</td>
			<td>{{run.title}}</td>
			<td>{{run.modified | date:"DATETIME_FORMAT"}}</td>
			{% endblock table_content %}
		</tr>
		{% endfor %}
	</tbody>
	<tfoot>
		<tr>
			{% block table_footer %}
			<th>Run</th>
			<th>Title</th>
			<th>Last modified</th>
			{% endblock table_footer %}
		</tr>
	</tfoot>
</table>
</div>
{% endblock %}

{% block footer_js%}
{{ block.super }}
<script src='{% static "thirdparty/DataTables/datatables.min.js" %}'></script>
<script src='{% static "thirdparty/DataTables/Buttons/js/dataTables.buttons.min.js" %}'></script>
<script src='{% static "thirdparty/DataTables/Buttons/js/buttons.bootstrap.js" %}'></script>
<script src='{% static "thirdparty/DataTables/Buttons/js/buttons.colVis.min.js" %}'></script>
<!-- page script -->
<script>
	{% block footer_js_data_table_config %}
	var data_table_config = {
		dom: 'Bflrtip',
		lengthMenu: [[20, 50, 100, -1], [20, 50, 100, "All"]],
		paging: true,
		lengthChange: true,
		searching: true,
		ordering: true,
		info: true,
		autoWidth: true,
		buttons: [
			{
				extend: 'colvis',
				postfixButtons: [ 'colvisRestore' ]
			},
			{
				extend: 'copy',
				text: 'Copy to clipboard'
			},'csv'
		],
		columnDefs: [
			{ type: "date", targets: 2 }
		],
		order: [[ 2, "desc" ]],
		stateSave: true, // saves
	}
	{% endblock footer_js_data_table_config %}

	$(function () {
		$("#tableruns").DataTable(data_table_config);
	});
    </script>
{% endblock %}

src/templates/catalog/run_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load catalog_filters %}

{% block header %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href='{% static "thirdparty/jquery.json-viewer/json-viewer/jquery.json-viewer.css" %}'>
{% endblock %}

{% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'catalog:list_iptss' %}">{{user.profile.instrument}}</a></li>
        {%if exp %}
        <li><a href="{% url 'catalog:list_runs' ipts exp %}">{{ipts}} :: {{exp}} </a></li>        
        {%else%}
        <li><a href="{% url 'catalog:list_runs' ipts %}">{{ipts}}</a></li>        
        {%endif%}        
		<li class="active">{{run.location}}</li>
    </ol>
</div>
{% endblock %}

{% block content %}
<div class="container">
	<div class="page-header">
        <h1>Run Detail <small> {{ run.metadata.scan_title }}</small></h1>
    </div>
    <div class="panel panel-default">
        <div class="panel-body"><div style="font-family: monospace;" id="json-renderer"></div></div>
    </div>    
</div>
{% endblock %}


{% block footer_js%}
{{ block.super }}
<script src='{% static "thirdparty/jquery.json-viewer/json-viewer/jquery.json-viewer.js" %}'></script>
<!-- page script -->
<script>
var data = {{run|remove_none|safe}};
if (Object.prototype.hasOwnProperty.call(data.metadata, "instrument")){
    delete data.metadata.instrument.instrument_xml;
}

$('#json-renderer').jsonViewer(data, {collapsed: false, withQuotes: false});
</script>
{% endblock %}