src/server/apps/catalog/urls.py
from django.conf.urls import url
from django.urls import path

from django.views.decorators.cache import cache_page

from . import views

urlpatterns = [

    # View IPTSs for an instrument
    url(r'^$',
        # cache_page(60*60)(views.IPTSs.as_view()), name='list_iptss'),
        (views.IPTSs.as_view()), name='list_iptss'),

    path('<int:intrument_id>/ajax/', views.IPTSsAjax.as_view(), name='list_iptss_ajax'),

    # Just for SNS
    # View all Runs for an instrument
    url(r'^(?P<ipts>[\w\-\.]+)/$',
        views.Runs.as_view(), name='list_runs'),
    url(r'^(?P<ipts>[\w\-\.]+)/ajax-table/$',
        views.RunsAjaxTable.as_view(), name='list_runs_ajax_table'),
    # run detail
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<filename>/SNS/[^\.]+(\.\w+)+)/$',
        views.RunDetail.as_view(), name='run_detail'),

    # HFIR has exp field
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/$',
        views.Runs.as_view(), name='list_runs'),
    # To Zip the contents of the ipts folder (Only HFIR)
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/zip/$',
        views.IptsZip.as_view(), name='zip_ipts'),

    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/ajax/$',
        views.RunsAjax.as_view(), name='list_runs_ajax'),
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/(?P<filename>/HFIR/[^\.]+\.[A-Za-z]{3})/$',
        views.RunDetail.as_view(), name='run_detail'),
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/(?P<filename>/HFIR/[^\.]+\.[A-Za-z]{3})/ajax/$',
        views.RunDetailAjax.as_view(), name='run_detail_ajax'),
    url(r'^(?P<ipts>[\w\-\.]+)/(?P<exp>exp[\d]+)/(?P<filename>/HFIR/[^\.]+\.[A-Za-z]{3})/file/$',
        views.RunFile.as_view(), name='run_file'),

]

src/server/apps/users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    url(r'^login$', views.LoginView.as_view(), name="login"),
    url(r'^logout$', views.LogoutView.as_view(), name="logout"),
    url(r'^profile$', views.ProfileView.as_view(), name="profile_view"),

    url(r'^profile/create$', views.ProfileCreate.as_view(), name="profile_create"),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileUpdate.as_view(), name="profile_update"),

    path('profile/<int:facility_id>/ajax/', views.InstrumentAjax.as_view(),
        name='list_instruments_ajax'),
]

src/server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Admin
    url(r'^admin/', admin.site.urls),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    # My apps
    url(r'^users/', include(('server.apps.users.urls', 'users'), namespace='users', )),
    url(r'^catalog/', include(('server.apps.catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^reduction/', include(('server.apps.reduction.urls',
                                 'reduction'), namespace='reduction')),
    url(r'^configuration/', include(('server.apps.configuration.urls',
                                     'configuration'), namespace='configuration')),
    url(r'^results/', include(('server.apps.results.urls', 'results'), namespace='results')),
    url(r'^util/', include(('server.util.urls', 'util'), namespace='util')),
    # Redirects all to Homepage
    url(r'^$', RedirectView.as_view(
        url=reverse_lazy('users:profile_view'), permanent=False),
        name='index',
        ),
    # Django remote REST API
    url(r'^api/', include('django_remote_submission.urls')),

]

if settings.DEBUG:
    # Serving files uploaded by a user during development
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/server/apps/users/models.py
from __future__ import unicode_literals

import logging
import re

from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, Group,
                                        PermissionsMixin, UserManager)
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.db import IntegrityError
from django.db.models import Q
from django.core.validators import RegexValidator
# from django.db.models.fields import BLANK_CHOICE_DASH

from server.apps.catalog.oncat.facade import Catalog
from server.apps.catalog.models import Facility, Instrument

logger = logging.getLogger(__name__)  # pylint: disable=C0103


class User(AbstractBaseUser, PermissionsMixin):
    '''
    This will overwrite the default user model
    '''
    username = models.CharField(max_length=40, unique=True, db_index=True,)
    email = models.EmailField(max_length=100, unique=False, blank=True)
    fullname = models.CharField(max_length=100, blank=False,
                                verbose_name=_("Full Name"))
    address = models.CharField(max_length=250, blank=False)

    date_joined = models.DateField(auto_now=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_full_name(self):
        return self.fullname

    def get_short_name(self):
        return self.username

    def __str__(self):
        return self.username


class UserProfileManager(models.Manager):
    '''
    Queries go here!!
    '''
    use_for_related_fields = True

    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset()


class UserProfile(models.Model):
    '''
    Adds some extra info the User class
    One to One relation
    '''

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="profile",
        related_query_name="profile",
    )

    facility = models.ForeignKey(Facility, on_delete=models.CASCADE)

    instrument = models.ForeignKey(Instrument, on_delete=models.CASCADE)

    ipts = models.CharField(
        "Integrated Proposal Tracking System (IPTS)",
        max_length=20,
        blank=True,
        # choices=BLANK_CHOICE_DASH,
        # validators=[
        #     RegexValidator(
        #         regex='^IPTS-\d+$',
        #         message='IPTS must be of the form: IPTS-XXXX',
        #         code='invalid_ipts'
        #     ),
        # ],
    )

    experiment = models.CharField(
        "Experiment (Only used at HFIR!)",
        max_length=20,
        blank=True,
        # choices=BLANK_CHOICE_DASH,
        # validators=[
        #     RegexValidator(
        #         regex='^exp\d+$',
        #         message='Exp must be of the form: expXXX',
        #         code='invalid_exp'
        #     ),
        # ],
    )

    def __str__(self):
        return self.user.username

    # Manager
    objects = UserProfileManager()

    # Meta
    class Meta:
        verbose_name = _("Profile")

src/server/apps/users/views.py
"""
    User management
"""
import json
import logging
import os

from natsort import natsorted
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import (REDIRECT_FIELD_NAME, authenticate,
                                 get_user_model)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.messages.views import SuccessMessageMixin
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse_lazy
from django.db.models import F
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import (CreateView, FormView, ListView, RedirectView,
                                  TemplateView, UpdateView)
from django_remote_submission.models import Server
from django.core import signing

from pprint import pformat
from server.settings.env import env
from django import forms

from .forms import UserProfileForm, LoginForm
from .models import UserProfile
from server.apps.catalog.models import Instrument
from server.apps.catalog.oncat.facade import Catalog

logger = logging.getLogger(__name__)


class LoginView(FormView):
    """

    """
    form_class = LoginForm
    template_name = 'users/login.html'
    redirect_field_name = REDIRECT_FIELD_NAME
    success_url = reverse_lazy('catalog:list_iptss')
    create_profile_url = reverse_lazy('users:profile_create')

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # This prints the password
        # logger.debug(request.POST)
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # Mathieu athentication
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        user = authenticate(self.request, username=username, password=password)
        if user is not None and not user.is_anonymous:
            logger.debug("Authenticating user %s...", username)
            auth_login(self.request, user)
            logger.debug("User %s authenticated.", username)
            # let's save the credentials to login on analysisis later
            self._save_credentials_in_session(password)
        else:
            messages.error(
                self.request,
                "Django Authenticate Failed. Invalid username or password!"
            )

        # Default authentication (NO PASSWORD!)
        # auth_login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        """
        Same as django.views.generic.edit.ProcessFormView.get()
        If the user is logged in anf hits: /users/login
        Rather than show the login form, redirect it to index
        """
        if request.user.is_authenticated:
            # Redirect to profile
            return redirect(reverse_lazy('catalog:list_iptss'))
        else:
            return super(LoginView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        try:
            UserProfile.objects.get(user=self.request.user)
        except ObjectDoesNotExist:
            logger.info("Redirecting to create user profile!")
            return self.create_profile_url

        redirect_to = self.request.GET.get(self.redirect_field_name, '/')
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to

    def form_invalid(self, form):
        messages.error(self.request, "Invalid username or password!")
        return super(LoginView, self).form_invalid(form)

    def _save_credentials_in_session(self, password):
        '''
        I need to save the password to authenticate in OnCat and analysis later
        TODO: Sessions should be saved in memory. See redis option also.
        '''
        logger.debug("Setting credentials in the session...")
        self.request.session["password"] = signing.dumps(password)


class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """
    url = reverse_lazy('users:login')

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        response = super(LogoutView, self).get(request, *args, **kwargs)
        return response

#
# Profile Catalog
#

class ProfileView(LoginRequiredMixin, TemplateView):

    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        '''
        If the user exists show the ProfileCatalog,
        otherwise redirect to create ProfileCatalog
        '''
        if UserProfile.objects.filter(user=request.user).count() > 0:
            return super(ProfileView, self).get(request, *args, **kwargs)
        else:
            return redirect(reverse_lazy('users:profile_create'))


class ProfileUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    '''
    I'm using form_class to test crispy forms
    '''
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'users/profile_form.html'
    # fields = '__all__'
    success_url = reverse_lazy('catalog:list_iptss')
    success_message = "Your Profile was updated successfully."

    def get_context_data(self, **kwargs):
        """
        """
        context = super().get_context_data(**kwargs)

        # Change the form population so we only show instruments for this facility
        context['form'].fields["instrument"].queryset = Instrument.objects.filter(
            facility_id=self.object.facility.id)
        # We change the form from text field to select box in the Form class
        # We need to popukate it with choices
        # This is the only way I found to have IPTS + EXP in the form when updated
        if self.object.ipts:
            context['form'].fields["ipts"].widget=forms.Select(
                choices=[(self.object.ipts, self.object.ipts)],
                attrs={"visible_reduction": "{}".format(self.object.instrument.visible_reduction) })
            if self.object.experiment:
                context['form'].fields["experiment"].widget=forms.Select(
                    choices=[(self.object.experiment, self.object.experiment)])
        # Put in the context all instruments for this facility
        context['instruments'] = json.dumps(list(Instrument.objects.filter(
            facility_id=self.object.facility.id).values(
                "id", "beamline", "name", "visible_reduction")))
        return context



class ProfileCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'users/profile_form.html'
    # fields = ['home_institution', 'email_address']
    success_url = reverse_lazy('catalog:list_iptss')
    success_message = "Your Profile was created successfully."

    def form_valid(self, form):
        '''
        Add user to the form as it is not shown to the user
        '''
        user = self.request.user
        form.instance.user = user
        return super().form_valid(form)



# class ProfileReductionUpdate(LoginRequiredMixin, SuccessMessageMixin,
#                              UpdateView):
#     '''
#     This will populate the form with the Catalog options
#     '''
#     model = UserProfile
#     form_class = UserProfileReductionForm
#     template_name = 'users/profile_reduction_form.html'
#     success_url = reverse_lazy('index')
#     success_message = "Your Profile for the Reduction was updated successfully."

#     def _fetch_iptss_from_the_catalog(self):

#         iptss = Catalog(
#             facility=self.request.user.profile.instrument.facility.name,
#             technique=self.request.user.profile.instrument.technique,
#             instrument=self.request.user.profile.instrument.catalog_name,
#             request=self.request,
#         ).experiments()

#         return iptss

#     def _get_iptss_info(self):
#         '''
#         '''
#         iptss = self._fetch_iptss_from_the_catalog()

#         filtered_iptss = [
#             {k: v for k, v in d.items() if k in ['ipts', 'title', 'exp']} for d in iptss]

#         iptss = [{'ipts': d['ipts'],
#                   'exp': [exp for exp in d.get('exp', []) if exp.startswith('exp')],
#                   'title': "{} :: {}".format(d['ipts'], d['title'])}
#             for d in filtered_iptss ]
#         return iptss

#     def get_context_data(self, **kwargs):
#         '''
#         Populates the context with the list of IPTSs and experiments
#         '''
#         context = super(ProfileReductionUpdate, self).get_context_data(**kwargs)
#         context['iptss'] = self._get_iptss_info()
#         logger.debug(pformat(context['iptss']))
#         return context


class InstrumentAjax(LoginRequiredMixin, TemplateView):
    '''
    Get the run detail but in ajax format
    '''

    def get(self, request, *args, **kwargs):

        facility_id = kwargs['facility_id']

        instruments_objs = Instrument.objects.filter(
            facility__id=facility_id,
            visible_catalog=True,
        ) #.order_by('beamline')

        # instruments_data = list(instruments_objs.values())
        instruments_data = list(instruments_objs.values(
            'id', 'beamline', 'name', 'visible_reduction',
        ))

        natsorted_instruments_data = natsorted(
            instruments_data, key=lambda i: i['beamline'])

src/templates/users/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block header %}
{{ block.super }}
<style>
.form-signin
{
    max-width: 330px;
    padding: 15px;
    margin: 0 auto;
}
.form-signin .form-signin-heading, .form-signin .checkbox
{
    margin-bottom: 10px;
}
.form-signin .checkbox
{
    font-weight: normal;
}
.form-signin .form-control
{
    position: relative;
    font-size: 16px;
    height: auto;
    padding: 10px;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
.form-signin .form-control:focus
{
    z-index: 2;
}
.form-signin input[type="text"]
{
    margin-bottom: -1px;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
.form-signin input[type="password"]
{
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
.account-wall
{
    margin-top: 20px;
    padding: 40px 0px 20px 0px;
    background-color: #f7f7f7;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}
.login-title
{
    color: #555;
    font-size: 18px;
    font-weight: 400;
    display: block;
}
.profile-img
{
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}
.need-help
{
    margin-top: 10px;
}
.new-account
{
    display: block;
    margin-top: 10px;
}

.disclaimer
{
    max-width: 800px;
    padding: 20px;
    margin: 0 auto;
}
</style>
{% endblock %}

{% block navbar %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}

<div class="container">
  <div class="page-header">
    <h1 align="center">HFIR &amp; SNS Data Reduction Service</h1>
  </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <h1 class="text-center login-title">Sign in to continue</h1>
            <div class="account-wall">
                <img class="profile-img" 
                    src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120"
                    alt="">
                <form class="form-signin" action="#" method="post">
                  {% csrf_token %}
                  {% crispy form %}
                </form>
            </div>
            <a href="#" class="text-center new-account">Need help?</a>
        </div>
    </div>
</div>

<div class="container disclaimer">
    <div class="well">
        <p align="justify">
            <b>NOTICE:</b> This is a Federal computer system and is the property of the United States Government. It is for authorized use only. Users (authorized or unauthorized) have no explicit or implicit expectation of privacy. Any or all uses of this system and all files on this system may be intercepted, monitored, recorded, copied, audited, inspected, and disclosed to authorized site, Department of Energy, and law enforcement personnel, as well as authorized officials of other agencies, both domestic and foreign. By using this system, the user consents to such interception, monitoring, recording, copying, auditing, inspection, and disclosure at the discretion of authorized site or Department of Energy personnel. Unauthorized or improper use of this system may result in administrative disciplinary action and civil and criminal penalties. By continuing to use this system you indicate your awareness of and consent to these terms and conditions of use. LOG OFF IMMEDIATELY if you do not agree to the conditions stated in this warning.
        </p>
    </div>
</div>

{% endblock %}

src/templates/users/profile_form.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}


{% block header %}
{{ block.super }}
<style>
/*jQuery UI autocomplete for bootstrap*/
.ui-autocomplete {
    position: absolute;
    height: 200px;
    overflow-y: scroll;
    z-index: 1000;
    top: 0;
    left: 0;
    cursor: default;
    background-color: #fff;
    padding:3px;
    border: 1px solid #ccc;
    font-size: 12px
}
.ui-autocomplete > li.ui-state-focus {
  background-color: #FF6C00;
}

</style>
{% endblock header %}

{% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{%if user.profile %}{% url 'users:profile_update' user.profile.pk %}{% endif %}">User Profile</a></li>
        <li class="active">{{ user }}</li>
    </ol>
</div>
{% endblock %}

{% block content %}

<div class="container">
    <div class="page-header">
        <h1>User Profile <small> {{ user }}</small></h1>
    </div>

    <div class="well">
        <div class="panel-body">
            {% crispy form  %}
        </div>
    </div>
</div>

{% endblock %}

{% block footer_js%}
{{ block.super }}

<script>

    // Setting up jQuery to pass csrf tokens to Django when using ajax.
	$.ajaxSetup({
        data: {
          csrfmiddlewaretoken: '{{ csrf_token }}'
        }
    });

    // set Instruments field
    function setInstrumentField(selector, jsonUrl, successCallback) {
        $.ajax({
            url : jsonUrl,
            type : 'get',
            dataType : 'json',
            success : function(data) {
                $(selector).empty();
                $(selector).append('<option selected">----------</option>');
                // [ {'value' : 123, 'label' : 'bof' }, ... ]
                data.map(element => {
                    $(selector).append($('<option>', {value: element.id, text: element.beamline + " :: " + element.name}));
                });
                successCallback(data);
            },
        });
    }

    // IPTS
    function setIPTSField(selector, jsonUrl, successCallback) {
        $.ajax({
            url : jsonUrl,
            type : 'get',
            dataType : 'json',
            //async : true,
            success : function(data) {
                // <input type="text" name="ipts" class="textinput textInput form-control" maxlength="20" id="id_ipts">
                //$(selector).replaceWith('<select name="ipts" class="textinput textInput form-control" maxlength="20" id="id_ipts"></select>');
                // $(selector).append('<option selected">----------</option>');
                // [ {'value' : 123, 'label' : 'bof' }, ... ]
                data.map(element => {
                    $(selector).append($('<option>', {value: element.ipts, text: element.ipts + " :: " + element.title}));
                });
                successCallback(data);
            },
        });
    }

    // global Variables
    // When editing the form, django pre-populates this variable.
    var instruments = {% if instruments %}{{instruments|safe}}{%else%}[]{%endif%};
    var iptss = [];


    // hide fields if there are no errors and if they are not empty
    if (!$("#div_id_instrument").hasClass( "has-error" ) && $("#id_instrument").val()==null)
       $("#div_id_instrument").hide();

    if (!$("#div_id_ipts").hasClass( "has-error" ) && $("#id_ipts").val()==null){
        $("#div_id_ipts").hide();
    }
    else if ($("#id_ipts").val() != null) {
        // On load
        var instrumentId = $("#id_instrument").val();
        instruments.forEach(function(element){
            if (element.id == instrumentId && element.visible_reduction == true){
                console.log("onload populating iptss");
                $(".loader").show();
                setIPTSField("#id_ipts", "{% url 'catalog:list_iptss_ajax' intrument_id=999 %}".replace(999, instrumentId), setIptss);
            }
        });

    }

    if (!$("#div_id_experiment").hasClass( "has-error" ) && $("#id_experiment").val()==null)
        $("#div_id_experiment").hide();



    // ajax is an async function needs a call back to set a global variable
    function setIptss(data){
        iptss = data;
        $(".loader").hide();
    }
    function setInstruments(data){
        instruments = data;
        $(".loader").hide();
    }

    // When the facility changes, update options the instrument field
    $('#id_facility').change(function(){

        console.log("Facility changed",  $(this));

        // $("#div_id_instrument").hide();
        $(".loader").show();

        $("#div_id_ipts").hide();
        $("#div_id_experiment").hide();
        var facilityId = $(this).val();
        $("#div_id_instrument").show();
        setInstrumentField("#id_instrument", "{% url 'users:list_instruments_ajax' facility_id=999 %}".replace(999, facilityId), setInstruments);

    });

    // When the instrument changes:
    // - update options the IPTS field if instrument.visible_reduction == true
    $('#id_instrument').change(function(){

        console.log("Instrument changed",  $(this));

        var instrumentId = $(this).val();
        var found = false;

        $("#id_ipts").empty();

        instruments.forEach(function(element){
            if (element.id == instrumentId && element.visible_reduction == true){
                console.log("Instrument available for reduction",  $(this));
                $(".loader").show();
                $("#div_id_experiment").hide();
                $("#div_id_ipts").show();
                setIPTSField("#id_ipts", "{% url 'catalog:list_iptss_ajax' intrument_id=999 %}".replace(999, instrumentId), setIptss);
                found = true;
            }
        });
        if (!found){
            console.log("Not found");
            $("#id_ipts").empty();
            $("#div_id_ipts").hide();

            $("#id_experiment").empty();
            $("#div_id_experiment").hide();

        }
    });

    // if IPTS changed
    $('#id_ipts').change(function(){

        $("#div_id_experiment").hide();
        var ipts = $(this).val();
        const iptsObj = iptss.find( element => element.ipts === ipts );
        if ('exp' in iptsObj){
            $("#id_experiment").empty();
            $("#div_id_experiment").show();
            iptsObj.exp.map(element => {
                if (element.startsWith("exp")){
                    $("#id_experiment").append($('<option>', {value: element, text: element}));
                }
            });
        }
    });


</script>

{% endblock %}

src/templates/users/userprofile_form.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{%if user.profile %}{% url 'users:profile_update' user.profile.pk %}{% endif %}">User Profile</a></li>
        <li class="active">{{ user }}</li>
    </ol>
</div>
{% endblock %}

{% block content %}

<div class="container">
    <div class="page-header">
        <h1>User Profile<small> {{ user }}</small></h1>
    </div>

    <div class="well">
        <div class="panel-body">
            {% crispy form  %}
        </div>
    </div>
</div>

{% endblock %}

{% block footer_js%}
{{ block.super }}
<script>

    // Smart selects changes the style of the drop down. Get it back!
    $('#id_instrument').addClass("select form-control")

    // Setting up jQuery to pass csrf tokens to Django when using ajax.
	$.ajaxSetup({
        data: {
          csrfmiddlewaretoken: '{{ csrf_token }}'
        }
    });

    // id = 'id_ipts', name = 'ipts'
    function replaceWithSelect(id, name ) {
        var value = $('#'+id).val();
        $('#'+id).replaceWith('<select name="'+name+'" class="select form-control" id="'+id+'"></select>');
        if (value){
            $('<option value="" selected>-------------------</option>').appendTo('#'+id);
            //$("<option value=" + value + " selected>" + value + "</option>").appendTo('#'+id);
        }
    };

    var iptss = [];
    function fetchIptsInfo(){
        $('#button-id-fecth_oncat').button('loading');
        // Those are IDs!
        var facility = $('#id_facility').val();
        var instrument = $('#id_instrument').val();
        var facilityName = $("#id_facility option:selected").text();
        if (!facility || !instrument){
            $.notify("You must select both Facility and Instrument to fetch information from the Catalog.", "warn");
            $('#button-id-fecth_oncat').button('reset'); 
            return;
        }
        // Tansform text fields into dropdowns. If they have value, assign to it (update view only!)
        replaceWithSelect('id_ipts','ipts');
        
        // Get all the IPTS and experiments for tthis instrument
        $.getJSON(
            "{% url 'catalog:list_iptss_ajax' 1234 5678 %}"
                .replace(1234, facility)
                .replace(5678, instrument),
            function (data) {
                iptss = data;
                $.each(data, function (i, value) {
                    var div_data = "<option value=" + value.ipts + ">" + value.ipts + " :: " + value.title + "</option>";
                    $(div_data).appendTo('#id_ipts');
            });
        });
        ('#id_experiment').value = "";
        if (facilityName == "HFIR"){
            $("#id_ipts").change( function () {
                console.log("IPTS changed...");
                replaceWithSelect('id_experiment','experiment');
                // Let's find the experiments for the select IPTS
                var selectedIpts = $(this).val();
                //console.log( "selected IPTS:",  selectedIpts);
                var iptsDetails = $.grep(iptss, function(e){ return e.ipts == selectedIpts; });
                console.log( iptsDetails );
                
                if (iptsDetails.length > 0){
                    replaceWithSelect('id_experiment','experiment');
                    $.each(iptsDetails[0].exp, function (i, value) {
                        if (i < iptsDetails[0].exp.length - 1){
                            console.log( value );
                            var div_data = "<option value=" + value + ">" + value + "</option>";
                            $(div_data).appendTo('#id_experiment');
                        }
                    });
                }
            });
        }
        $('#button-id-fecth_oncat').button('reset');        
    };

    
</script>
{% endblock %}