src/server/apps/results/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

from .views import *

urlpatterns = [
     # Configurations
    url(r'^$', JobsList.as_view(), name='job_list'),
    url(r'^(?P<pk>\d+)$', JobDetail.as_view(), name='job_detail'),
    url(r'^livelog/(?P<pk>\d+)$', JobLiveLog.as_view(), name='job_log_live'),
    url(r'^live$', TemplateView.as_view(template_name='results/job_live.html'), name='job_list_live'),
    url(r'^zipfiles$', ZipFilesView.as_view(), name='zipfiles'),

    # Cache for 60 * 15 seconds
    # url(r'^result/(?P<pk>\d+)/plot$', cache_page(60 * 15)(ResultPlot.as_view()), name='result_plot'),
]

src/server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Admin
    url(r'^admin/', admin.site.urls),
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    # My apps
    url(r'^users/', include(('server.apps.users.urls', 'users'), namespace='users', )),
    url(r'^catalog/', include(('server.apps.catalog.urls', 'catalog'), namespace='catalog')),
    url(r'^reduction/', include(('server.apps.reduction.urls',
                                 'reduction'), namespace='reduction')),
    url(r'^configuration/', include(('server.apps.configuration.urls',
                                     'configuration'), namespace='configuration')),
    url(r'^results/', include(('server.apps.results.urls', 'results'), namespace='results')),
    url(r'^util/', include(('server.util.urls', 'util'), namespace='util')),
    # Redirects all to Homepage
    url(r'^$', RedirectView.as_view(
        url=reverse_lazy('users:profile_view'), permanent=False),
        name='index',
        ),
    # Django remote REST API
    url(r'^api/', include('django_remote_submission.urls')),

]

if settings.DEBUG:
    # Serving files uploaded by a user during development
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/server/apps/results/views.py
import numpy as np
import plotly.graph_objs as go
from plotly.offline import plot
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.views.generic import DetailView, ListView
from django_remote_submission.models import Job, Result
from django.contrib import messages
import os
import zipfile
from io import StringIO
from django.views import View
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from tempfile import NamedTemporaryFile
from server.apps.reduction.models.abstract import ModelMixin
import logging

logger = logging.getLogger(__name__)  # pylint: disable=C0103

# For the job details to share the same function as the sans models
Job.get_all_fields = ModelMixin.get_all_fields


class JobMixin(object):

    def get_queryset(self):
        '''
        Make sure the user only accesses its Jobs
        '''
        return Job.objects.filter(owner=self.request.user)


class JobsList(LoginRequiredMixin, JobMixin, ListView):
    template_name = 'results/job_list.html'


class JobLiveLog(LoginRequiredMixin, JobMixin, DetailView):
    template_name = 'results/log_live.html'

    def get_queryset(self):
        queryset = super(JobLiveLog, self).get_queryset()
        return queryset.filter(id=self.kwargs['pk'])

class JobDetail(LoginRequiredMixin, JobMixin, DetailView):

    def get_template_names(self):
        """
        ** Overload **
        Returns a list of priority templates to render. From specific to general.
        technique/facility/instrument/self.template
        technique/facility/self.template
        technique/self.template
        self.template
        Note that the method calling this must have self.template_name defined!!
        """

        facility_name = self.request.user.profile.instrument.facility.name.lower()
        instrument_name = self.request.user.profile.instrument.name.lower()
        technique_name = self.request.user.profile.instrument.technique.lower()
        return [
            os.path.join('results', technique_name, facility_name,
                         instrument_name, 'job_detail.html'),
            os.path.join('results', technique_name, facility_name,
                         'job_detail.html'),
            os.path.join('results', technique_name, 'job_detail.html'),
            os.path.join('results', 'job_detail.html'),
        ]


    def get_queryset(self):
        queryset = super(JobDetail, self).get_queryset()
        return queryset.filter(id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(
            JobDetail,
            self).get_context_data(**kwargs)

        files_to_plot = [
            result.local_file.path for result in self.object.results.all()
        ]
        if len(files_to_plot) == 0:
            logger.warning("No files to plot!")
            context['plot'] = None
        else:
            try:
                context['plot'] = self.plot_sasview_multiple_iq(files_to_plot)
            except Exception as e:
                messages.error(
                    self.request, "An exception occurred while trying to plot the \
                    data: {0} :: {1}".format(type(e).__name__, str(e)))
                logger.exception(e)
        return context

    def plot_sasview_multiple_iq(self, files_to_plot):
        data_list = []
        for filepath in files_to_plot:
            with open(filepath, 'rb') as f:
                # Only way to read CVV and TSV
                clean_lines = (line.replace(b',', b'\t') for line in f)
                data = np.genfromtxt(
                    clean_lines,
                    delimiter="\t",
                    skip_header=2,
                    names=['X', 'Y', 'E', 'DX'],
                )
                # logger.debug(data)

                x_data = data['X']
                y_data = data['Y']
                e_data = data['E']
                trace = go.Scatter(
                    name=filepath.split('/')[-1],
                    x=x_data,
                    y=y_data,
                    error_y=dict(
                        type='data',
                        array=e_data,
                        visible=True
                    ),
                    mode='lines+markers',
                )
                data_list.append(trace)

        layout = go.Layout(
            autosize=False,
            width=1024,
            height=800,
            xaxis=dict(
                autorange=True
            ),
            yaxis=dict(
                autorange=True
            )
        )
        fig = go.Figure(data=data_list, layout=layout)
        plot_div = plot(fig, output_type='div', include_plotlyjs=False)
        return plot_div


class ZipFilesView(LoginRequiredMixin, JobMixin, View):
    def post(self, request):

        from pprint import pprint
        pprint(request.POST)

        ids_selected = request.POST['ids_selected']

        if ids_selected:
            ids_selected_arr = ids_selected.split(',')

        filenames = []
        for job_in in ids_selected_arr:
            r = Result.objects.get(id=job_in)
            if r.job.owner != request.user:
                return HttpResponseForbidden()
            filenames.append(r.local_file.path)

        zip_file = NamedTemporaryFile()
        with zipfile.ZipFile(zip_file.name, 'w') as myzip:
            for f in filenames:
                myzip.write(f, os.path.basename(f))

        resp = HttpResponse(
            zip_file.read(),
            content_type='application/zip'
        )
        return resp

src/templates/results/job_list.html
{% extends "base.html" %}

{% load staticfiles %}
 
{% block header %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href='{% static "thirdparty/DataTables/datatables.min.css" %}'>
<link rel="stylesheet" type="text/css" href='{% static "css/results.css" %}'>
{% endblock %}

{% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li class="active">Job List</li>
    </ol>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Jobs<small> list</small></h1>
    </div>

    <table id="table_configuration" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Job Title</th>
                <th>Status</th>
                <th>Date modified</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{object.id}}</td>
                <td>
                <a href="{% url 'results:job_detail' object.id %}"
                   title="Click to see the details of this Job."><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span> {{object.title}}</a>
                </td>
                <td><span class="label label-{{object.status}}">{{object.status }}</span></td>
                <td>{{object.modified | date:"DATETIME_FORMAT" }}</td>
                
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>Id</th>
                <th>Job Title</th>
                <th>Status</th>
                <th>Date modified</th>
            </tr>
        </tfoot>
    </table>
</div>
{% endblock %}

{% block footer_js%}
{{ block.super }}
<script src='{% static "thirdparty/DataTables/datatables.min.js" %}'></script>
<!-- page script -->
<script>
        $(function () {
            $("#table_configuration").DataTable({
                "lengthMenu": [[20, 50, 100, -1], [20, 50, 100, "All"]],
                "order": [[ 3, 'desc' ]],
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": true
            });
        });
    </script>
{% endblock %}

src/templates/results/job_live.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href='{% static "css/results.css" %}'>
{% endblock %}

{% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li class="active">Live results</li>
    </ol>
</div>
{% endblock %}

{% block content %}
<div class="container">

    <div class="page-header">
        <h1>Live results for <small>{{user.profile.instrument}}</small></h1>
    </div>
    <table class="table table-hover">
        <thead>
            <th>ID</th>
            <th>Title</th>
            <th>Status</th>
            <th>Modified</th>
        </thead>
        <tbody id="job-status-rows"></tbody>
	</table>
</div>
{% endblock %}

{% block footer_js%}
{{ block.super }}
<script src='{% static "thirdparty/reconnecting-websocket/reconnecting-websocket.min.js" %}'></script>
<script>

var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
socket = new ReconnectingWebSocket(ws_scheme + "://" + window.location.host + "/ws/job-user/");


socket.onmessage = function(e) {
  var { job_id, title, status, modified } = JSON.parse(e.data),
      tbody = $('#job-status-rows'),
      trs = tbody.children(),
      tr = $('<tr>').append(
        $('<td>').text('' + job_id)
      ).append(
        //$('<td>').text('' + title)
          $('<td>').append('<a href="' + "{% url 'results:job_log_live' 999 %}".replace (999, job_id) +
                   '" title="Click to see the Live Log of this Job."><span class="glyphicon glyphicon-tasks" aria-hidden="true"></span> ' +
                   title + ' {{object.title}}</a>')
      ).append(
        //$('<td>').text('' + status)
        $('<td>').append('<span class="label label-' + status + '">' + status + '</span>')
      ).append(
        $('<td>').text('' + (new Date(Date.parse(modified))).toLocaleString())
      ),
      found = false;
  trs.each((i, el) => {
    var id = +el.firstChild.textContent;
    if (id === job_id) {
      $(el).replaceWith(tr);
      found = true;
      return false;
    }
  });
  if (!found) {
    tr.appendTo(tbody);
  }
  trs = tbody.children();
  trs.sort((a, b) => {
    return b.lastChild.textContent.localeCompare(a.lastChild.textContent);
  });
  trs.detach().appendTo(tbody);
}

socket.onopen = function() { }

// Call onopen directly if socket is already open
if (socket.readyState == WebSocket.OPEN) socket.onopen();

</script>
{% endblock %}

src/templates/results/live.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href='{% static "css/results.css" %}'>
{% endblock %}

{% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li class="active">Live results</li>
    </ol>
</div>
{% endblock %}

{% block content %}
<div class="container">
	
    <div class="page-header">
        <h1>Live results for <small>{{user.profile.instrument}}</small></h1>
    </div>
    <table class="table table-hover">
        <thead>
            <th>ID</th>
            <th>Title</th>
            <th>Status</th>
        </thead>
        <tbody id="job-status-rows"></tbody>
	</table>
</div>
{% endblock %}

{% block footer_js%}
{{ block.super }}
<script>

socket = new WebSocket("ws://" + window.location.host + "/job-user/");

socket.onmessage = function(e) {
  var { job_id, title, status } = JSON.parse(e.data);
  $('#job-status-rows').append(
    $('<tr>').append(
      $('<td>').text('' + job_id)
    ).append(
      $('<td>').text('' + title)
    ).append(
      //$('<td>').text('' + status)
      $('<td>').append('<span class="label label-' + status + '">' + status + '</span>')
    )
  );
}
socket.onopen = function() { }

// Call onopen directly if socket is already open
if (socket.readyState == WebSocket.OPEN) socket.onopen();

</script>
{% endblock %}

src/templates/results/log_live.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
{{ block.super }}
<style>
pre {
  display:block;
  font:normal 12px/22px Monaco,Monospace !important;
  color:black;
  background-color:#DCDCDC;
  background-image:-webkit-repeating-linear-gradient(top, #F8F8FF 0px, #F8F8FF 22px, white 22px, white 44px);
  background-image:-moz-repeating-linear-gradient(top, #F8F8FF 0px, #F8F8FF 22px, white 22px, white 44px);
  background-image:-o-repeating-linear-gradient(top, #F8F8FF 0px, #F8F8FF 22px, white 22px, white 44px);
  background-image:repeating-linear-gradient(top, #F8F8FF 0px, #F8F8FF 22px, white 22px, white 44px);
  padding:0em 1em;
  overflow:auto;
}
</style>
{% endblock %}

{% block breadcrumbs %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'results:job_list_live'%}">Jobs Live list</a></li>
        <li class="active">Log live for {{object}}</li>
    </ol>
</div>
{% endblock %}

{% block content %}
<div class="container">

    <div class="page-header">
        <h1>Live Log results for <small>{{object}}</small></h1>
    </div>

    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">Log for Job :: <a href="{% url 'results:job_detail' object.id %}"
                   title="Click to see the Results of this Job."><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span> {{object.title}}</a></div>
            <div class="panel-body">
               <pre id="job-log-rows"></pre>
            </div>
        </div>
    </div>

    <p>Click <a href="{% url 'results:job_detail' object.id %}"
                   title="Click to see the details of this Job."><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span>here</a> to see the details of this job</p>

</div>
{% endblock %}

{% block footer_js%}
{{ block.super }}

<script src='{% static "thirdparty/reconnecting-websocket/reconnecting-websocket.min.js" %}'></script>
<script>

var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
socket = new ReconnectingWebSocket(ws_scheme + "://" + window.location.host + "/ws/job-log/{{ object.id }}/");
socket.onmessage = function(e) {
    var { log_id, time, content, stream } = JSON.parse(e.data);
//    $('#job-log-rows').append(
//        '\n' +
//        log_id + " -\t" +
//        (new Date(Date.parse(time))).toLocaleString()  + "\t" +
//        stream + "\t" + content
//    );
    $('#job-log-rows').append(content);
    $("html, body").animate({ scrollTop: $(document).height() }, 0);
}
socket.onopen = function() { }
// Call onopen directly if socket is already open
if (socket.readyState == WebSocket.OPEN) socket.onopen();

</script>
{% endblock %}